exp508:
  alternatives:
    - control
    - alternative
  metadata:
    control:
      name: bob
    alternative:
      name: derp
  regions:
    - us
  resettable: true
  window_of_time_for_conversion_in_minutes: 1
  retain_user_alternatives_after_reset: false
exp123:
  alternatives:
    - control
    - alternative
  regions:
    - us
  resettable: true
  goals:
    - goal1
    - goal2
    - goal3
  window_of_time_for_conversion_in_minutes: 1
  retain_user_alternatives_after_reset: true
exp456:
  alternatives:
    - control
    - alternative
  regions:
    - us
  resettable: true
  window_of_time_for_conversion_in_minutes: 1
